///////////////////////////////////////////////////////////////
// ItemFactory.cs - generates DBElements of definitive       //
//                  structure.                               //
// Ver 1.0                                                   //
// Application: Demonstration for CSE687-OOD, Project#2      //
// Language:    C#, ver 6.0, Visual Studio 2015              //
// Platform:    Dell XPS2700, Core-i7, Windows 10            //
// Author:      Will Zhang,  Syracuse University             //
//              (315) 383-3757, tzhan116@syr.edu             //
///////////////////////////////////////////////////////////////
/*
 * Package Operations:
 * -------------------
 * This package implements operations of ItemFactory<Value, DBelement> where Value 
 * is generic and wraps the value into database Element of definitive 
 * structure, that is, DBElement<Key, Data>.
 *
 * This is to ensure that all the database elements are of the same 
 * structure, even if generated by other parts of the software.
 *
 */
/*
 * Maintenance:
 * ------------
 * Required Files: DBEngine.cs, DBElement.cs, and
 *                 UtilityExtensions.cs only if you enable the test stub
 *
 * Build Process:  devenv Project2Starter.sln /Rebuild debug
 *                 Run from Developer Command Prompt
 *                 To find: search for developer
 *
 * Maintenance History:
 * --------------------
 *
 * ver 1.0 : 01 Oct 15
 * - first release
 *
 */
//todo add placeholders for Shard
//todo add reference to class text XML content

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using static System.Console;

namespace Project2Starter
{
    //public class ItemFactory<Value, DBElement>
    //{
    //    public ItemFactory()
    //    {

    //    }

    //    public bool ItemGenerator(Value val, out DBElement elem)
    //    {
    //        if(!ValidValue(val))
    //        {
    //            elem = default(DBElement);
    //            return false;
    //        }
    //        else
    //        {
                
    //        }
    //    }

        public 
        static void Main(string[] args)
        {
        }
    //}
}
